# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 12:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
